sudo: required

language: python

services:
  - docker

env:
  global:
    - PORTS="8080:8080"
    - DAEMONIZE="1"
    - DOCKER_REPO="laslabs/alpine-red-october"
    - DOCKER_USER="laslabsbot"
    - DOCKER_TAG="latest"
    # DOCKER_PASS
    - secure: "a0+1/WQfPd6099q8eQALGB4lD1SGJPJ3DViZ50mD1kPm5Joh88hyC8HyIDQmVohfdfOklL0utF1cQ+A7rTsUBSy6GpsSi/jFoOOhZW3d4lisQQo2qjH7WETAl6MvEkRTSHNUzyzkgCBppno5kySvVjAQuib3M4yDS6otYsYfg1vNeIslC6VxsEGN7K9RVqVbAQZxxXbHmfyeGPsJZOLJ/0btoYnrPF8mpYrItZB5XVDu/eC+wAsaXmfv/0gylalobqud0/tnBLtfR/FUD14cH2qs+y7ulqQHQQclRAxDr6SCnEhLRadGmawSwsUcMDFXbpVoXQLbxwLmolSXbLVSpl+AE3rggA/qrx1xDoAa8EvB0MnZXL03gIiUPIjU1G1T4CWBD5Twph8Kvu2s5sppOcUuZ1kWC9Nel/Dt6mJOjn4SaZW6nUkl5zLgnCLwbD2pnZNi2IV5UXDBGIj96A5A1BBV6BdnPXhqu12bMWg80y26vf11y2SNA3wcoywmd4VP1B26Rd/eHGdFZbH8uVPqVUjK26VWkgz1eVBfPKRbirdKXykInIvnqAU1LFEEQ6Ej+QpxwaRRXI83sihOxmPvPveNmeLVFWUEgRWmHzBfOfrVDOKoBwMRdzWSlTxhwf+qM5/nmkWxoI39K8dyRI6tPFjA2fAE1fJ+rC8qqGpxojI="

  matrix:
    - TESTS="1"
    - LINT_CHECK="1" LINT_IGNORE="SC2086"
    - HUB="1"

install:
  - git clone --depth=1 https://github.com/LasLabs/docker-quality-tools.git ${HOME}/docker-quality-tools
  - export PATH=${HOME}/docker-quality-tools/travis:${PATH}
  - travis_install_all

script:
  - travis_run_all

after_success:
  - travis_after_success_all
